global:
  resolve_timeout: 5m
  smtp_smarthost: 192.168.50.254:25
  smtp_from: alerts@ocp4.example.com
  smtp_require_tls: false
receivers:
- name: email-notification
  email_configs:
    - to: ocp-admins@example.com
- name: default
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: default
  repeat_interval: 1m
  routes:
  - match:
    receiver: default
      alertname: Watchdog
  - match:
    receiver: email-notification
      severity: warning
