global:
  resolve_timeout: 5m
  smtp_smarthost: 
  smtp_from: 
  smtp_require_tls: 
receivers:
- name: 
  email_configs:
    - to: 
- name: null
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: null
  repeat_interval: 12h
  routes:
  - match:
    receiver: null
      alertname: 
